# Generated by Django 5.1.4 on 2026-05-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anthropic_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
