# Generated by Django 5.1.4 on 2026-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_anthropic_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='llm_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='llm_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (ChatGPT)')], default='anthropic', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
