# Generated by Django 5.1.4 on 2026-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(choices=[('cro', 'Conversion rate'), ('seo', 'SEO'), ('compliance', 'Site compliance'), ('gmc', 'Google Merchant Center')], default='cro', max_length=16),
        ),
        migrations.AddField(
            model_name='audit',
            name='report',
            field=models.JSONField(blank=True, default=dict, help_text='Long-form structured report (used by compliance/gmc types).'),
        ),
    ]
