# Generated by Django 5.1.4 on 2026-05-13 12:31

from django.db import migrations, models


def backfill_group_slug(apps, schema_editor):
    """Pre-bundle audits share their own slug as the group — old /audit/<slug>
    URLs still resolve as a single-type bundle."""
    Audit = apps.get_model("audits", "Audit")
    Audit.objects.filter(group_slug="").update(group_slug=models.F("slug"))


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_auditlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='group_slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Shared id for an audit bundle. All four audit types created from one public submission share this slug — the public page fetches by group_slug and renders four tabs.', max_length=24),
        ),
        migrations.RunPython(backfill_group_slug, migrations.RunPython.noop),
    ]
