# Generated by Django 5.1.4 on 2026-05-10 06:24

import django.db.models.deletion
import sites.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('token', models.CharField(default=sites.models._site_token, editable=False, max_length=64, unique=True)),
                ('sampling', models.PositiveSmallIntegerField(default=50, help_text='Percentage of visitors who see variants (0-100).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'domain'), name='uniq_user_domain')],
            },
        ),
    ]
